Repository tony9402/solutions_for_baekjoon_problems, pull requests merged in 2022-10, with the labels that each got.

#2 [ADD] 11441 python solution
  prefix_sum/11441/main.py
Labels: Python, Solution, Accepted

#6 [ADD] 11441 cpp solution
  prefix_sum/11441/main.cpp
Labels: C++, Solution, Accepted

#5 [ADD] 11728 python solution
  two_pointer/11728/main.py
Labels: Python, Solution, Accepted

#9 [ADD] 11441 java solution
  prefix_sum/11441/Main.java
Labels: Java, Solution, Accepted

#13 [ADD] 12026 java solution
  dynamic_programming_1/12026/Main.java
Labels: Java, Solution, Accepted

#15 [ADD] 2156 python Solution
  dynamic_programming_1/2156/main.py
Labels: Python, Solution, Accepted

#16 [ADD] 2156 cpp Solution
  data_structure/2156/main.cpp
Labels: C++, Solution, Accepted

#17 [ADD] 4949 cpp solution
  data_structure/4949/main.cpp
Labels: C++, Solution, Accepted

#18 add 2609 python solution
  math/2609/main.py
Labels: Python, Solution, Accepted

#19 [ADD] 1110 python solution
  math/1110/main.py
Labels: Python, Solution, Accepted

#10 [ADD] 3025 CPP Solution
  simulation/3025/main.cpp
Labels: C++, Solution
